development:
  AWS_ACCESS_KEY_ID: "AKIAJRVLSOCJ7XOEVUGA"
  AWS_SECRET_ACCESS_KEY: "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"
  S3_BUCKET: "rails-store-bucket"
test:
  AWS_ACCESS_KEY_ID: "PAST KEY ID HERE"
  AWS_SECRET_ACCESS_KEY: "PASTE SECRET ACCESS KEY HERE"
  S3_BUCKET: "rails-store-bucket"
production:
  AWS_ACCESS_KEY_ID: "PAST KEY ID HERE"
  AWS_SECRET_ACCESS_KEY: "PASTE SECRET ACCESS KEY HERE"
  S3_BUCKET: "rails-store-bucket"